#!/usr/bin/env python3

import os

os.system(
    'clang++ '
        '-std=c++17 '
        '-Wall -Wextra -pedantic '
        '-Wno-char-subscripts '
        '-fsanitize=address,undefined '
        'main.cc && ./a.out '
)
