#!/usr/bin/env python3

import os

def isValidDir() -> bool:
    dirs = os.getcwd().split('/')
    if len(dirs) < 2: return False
    dirs = dirs[-2:]
    if dirs[0] != "Leetcode": return False
    # question = dirs[1].split('-')
    # if not question[0].isalnum(): return False
    return True

def filesAreReady(filenames: list[str]) -> bool:
    return "prob.cc" in filenames

def alreadyInitialized(filenames: list[str]) -> bool:
    if "main.cc" in filenames or "a.out" in filenames: return True
    for filename in filenames:
        if "prac" in filename: return True
    return False

if __name__ == "__main__":
    if not isValidDir():
        print("nprob: error: invalid directory to run")
        exit(1)

    filenames = sorted([f for f in os.listdir('.') if os.path.isfile(f)])
    if not filesAreReady(filenames):
        print("nprob: error: 'prob.cc' does not exist")
        exit(1)
    if alreadyInitialized(filenames):
        print("nprob: error: this problem is already initialized")
        exit(1)

    # copy problem template to new soln.cc
    os.system(f'cp prob.cc soln.cc')
    # copy main_template.cc to current main
    os.system(f'cp ../snippets/main_template.cc main.cc')
    # open new soln.cc and main using vscode
    os.system(f'code soln.cc main.cc')

    exit(0)

    

