#!/usr/bin/env python3

import os, sys

INCLUDE = '#include "../utils.h"'

def isValidDir(mode: int) -> bool:
    dirs = os.getcwd().split('/')
    if len(dirs) < 2: return False
    if mode == 0:
        if dirs[-2] != "Leetcode": return False
    elif mode == 1:
        if dirs[-1] != "Leetcode": return False
    return True

def filesAreReady(filenames: list[str]) -> bool:
    return "prob.cc" in filenames

def alreadyInitialized(filenames: list[str]) -> bool:
    if "main.cc" in filenames or "a.out" in filenames: return True
    for filename in filenames:
        if "prac" in filename: return True
    return False

if __name__ == "__main__":
    argv = sys.argv
    if len(argv) > 2:
        print("usage: nprob [name]")
        exit(1)
    mode = len(argv) - 1

    if not isValidDir(mode):
        print("nprob: error: invalid directory to run")
        exit(1)

    if mode == 0:
        filenames = sorted([f for f in os.listdir('.') if os.path.isfile(f)])
        if not filesAreReady(filenames):
            print("nprob: error: 'prob.cc' does not exist")
            exit(1)
        if alreadyInitialized(filenames):
            print("nprob: error: this problem is already initialized")
            exit(1)

        # add common includes if not already added
        with open("prob.cc", "r+") as file:
            firstline = file.readline() or ""
            if firstline != INCLUDE:
                prevLines = firstline + file.read()
                file.seek(0)
                file.write(INCLUDE + "\n\n" + prevLines)

        # copy problem template to new soln.cc
        os.system(f'cp prob.cc soln.cc')
        # copy main_template.cc to current main
        os.system(f'cp ../snippets/main_template.cc main.cc')
        # open new soln.cc and main using vscode
        os.system(f'code soln.cc main.cc')
    elif mode == 1:
        dirname = argv[1].replace(' ', '_').replace('.', '')
        if dirname in [dir for dir in os.listdir('.') if os.path.isdir(dir)]:
            print(f'nprob: warning: directory \'{dirname}\' already existed, continuing...')
        else:
            print(f'nprob: creating directory \'{dirname}\', continuing...')
            os.system(f'mkdir \'{dirname}\'')
        os.system(f'code \'{dirname}/prob.cc\'')

    exit(0)

    

